---
# As Ubuntu 14.04 LTS has no Java 8, we need these 3 tasks
# TODO This should be in a seperate role (and repo), since it is needed
# in other roles, too (e.g. CDMI)
- name: Add Java 8 Repository
  apt_repository:
    repo: ppa:webupd8team/java
    state: present

- name: Accept Oracle license
  debconf:
    name: oracle-java8-installer
    question: shared/accepted-oracle-license-v1-1
    vtype: select
    value: "true"

- name: Install Java 8
  apt:
    name: oracle-java8-installer
    state: present
    update_cache: yes

