---
- include: java8.yml
  when: ansible_distribution == "Ubuntu"

- name: Install git
  package: name=git state=present

- name: Create tmp dir
  file: path={{ tmp_dir }} state=directory
  # If the tmp dir existed before, we won't delete it in the end
  notify:
    - remove tmp dir


- name: Clone CDMI repo
  git:
    repo: "https://github.com/indigo-dc/CDMI.git"
    dest: "{{ tmp_dir }}/git-repo"

- name: Install rpm package
  yum:
    name: "{{ tmp_dir }}/git-repo/cdmi-server-{{ cdmi_version }}-1.el7.centos.x86_64.rpm"
  when: ansible_pkg_mgr == "yum"

- name: Install deb package
  apt:
    deb: "{{ tmp_dir }}/git-repo/cdmi-server-{{ cdmi_version }}.deb"
  when: ansible_pkg_mgr == "apt"
