---
- include: java8.yml
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14"

- include: "{{ ansible_pkg_mgr }}.yml"

- name: Start and enable CDMI service
  service:
    name: cdmi-server
    state: started
    enabled: yes
