---
- include: java8.yml
  when: ansible_distribution == "Ubuntu"

- include: "{{ ansible_pkg_mgr }}.yml"

- name: Start and enable CDMI service
  service:
    name: cdmi-server
    state: started
    enabled: yes
