---
- name: Uninstall CDMI for CentOS package
  yum:
    name: "{{ cdmi_pkg_name }}"
    state: absent
  when: rpm_get_url is defined

- name: Download/Install CDMI for CentOS package
  yum:
    name: "{{ rpm_get_url }}"
    state: present
    validate_certs: no
  notify:
    - Restart CDMI
  when: rpm_get_url is defined


- name: Install CDMI package
  yum:
    name: "{{ cdmi_pkg_name }}"
    state: latest
    update_cache: yes
  when: rpm_get_url is undefined
